version: "3.9"

name: cloud_native_auth

services:
  auth-api-servcie:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./auth_service:/code
    networks:
      - auth-network
  todos-api-servcie:
    build:
      context: ./todo_service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./todo_service:/code
    networks:
      - auth-network

networks:
  auth-network: